stages:
- name: Deploy--Set Environment variables
  steps:
  - envFrom:
    - sourceKey: API_TOKEN
      sourceName: pipeline-api-key
      targetKey: rancher_api_token
    - sourceKey: rancher-url
      sourceName: rancher
      targetKey: rancher_url
    runScriptConfig:
      image: iiiorg/rancher-cli:v2.4.6
      shellScript: rancher login ${rancher_url} -t ${rancher_api_token} --skip-verify
        && rancher kubectl delete configmap -n ${CICD_GIT_REPO_NAME} ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-env
        --ignore-not-found=true && rancher kubectl create configmap -n ${CICD_GIT_REPO_NAME}
        ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-env --from-env-file=iiidevops/app.env
        && rancher kubectl annotate configmap -n ${CICD_GIT_REPO_NAME} ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-env
        iiidevops.org/project_name=${CICD_GIT_REPO_NAME} iiidevops.org/branch=${CICD_GIT_BRANCH}
        iiidevops.org/commit_id=${CICD_GIT_COMMIT} iiidevops.org/type=appenv
  when:
    branch:
      include:
      - master

- name: Deploy--ElasticSearch
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch:
      include:
      - master

- name: Deploy--ElasticSearch-service
  steps:
  - applyYamlConfig:
      path: ./service.yaml
  when:
    branch:
      include:
      - master

- name: Deploy--ElasticSearch-gui
  steps:
  - applyYamlConfig:
      path: ./service-gui.yaml
  when:
    branch:
      include:
      - master
