apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-gui
  namespace: ${CICD_GIT_REPO_NAME}
  labels: 
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-gui
  annotations:
    iiidevops.org/project_name: ${CICD_GIT_REPO_NAME}
    iiidevops.org/branch: ${CICD_GIT_BRANCH}
    iiidevops.org/commit_id: ${CICD_GIT_COMMIT}
    iiidevops.org/type: db-gui
spec:
  type: NodePort
  selector:
    run: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-eshead
  ports:
    - name: es-tcp-9100
      protocol: TCP
      port: 9100
